version: '3.9'

services:
    app:
        build:
            context: .
        ports:
            - '${PORT}:${PORT}'
        environment:
            NODE_ENV: ${NODE_ENV}
            LOG_LEVEL: ${LOG_LEVEL}
        env_file:
            - .env
